title: Danu Jaya Saputro # your name (or website title) here
logo: 
![Me](Danu.png)
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Data Science Enthusiast 
  <br><br>
  <a href="https://www.linkedin.com/in/danu-jaya-saputro-ab9463b2/">View My LinkedIn Profile</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
